//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Lending
{
    using Codat.Lending.Models.Components;
    using Codat.Lending.Models.Errors;
    using Codat.Lending.Utils;
    using System;

    public interface ITransactions
    {
        public IAccountTransactions AccountTransactions { get; }
        public IDirectCosts DirectCosts { get; }
        public IJournalEntries JournalEntries { get; }
        public IJournals Journals { get; }
        public ITransfers Transfers { get; }
    }

    public class Transactions: ITransactions
    {
        public SDKConfig SDKConfiguration { get; private set; }
        private const string _language = "csharp";
        private const string _sdkVersion = "9.0.0";
        private const string _sdkGenVersion = "2.463.0";
        private const string _openapiDocVersion = "3.0.0";
        private const string _userAgent = "speakeasy-sdk/csharp 9.0.0 2.463.0 3.0.0 Codat.Lending";
        private string _serverUrl = "";
        private ISpeakeasyHttpClient _client;
        private Func<Codat.Lending.Models.Components.Security>? _securitySource;
        public IAccountTransactions AccountTransactions { get; private set; }
        public IDirectCosts DirectCosts { get; private set; }
        public IJournalEntries JournalEntries { get; private set; }
        public IJournals Journals { get; private set; }
        public ITransfers Transfers { get; private set; }

        public Transactions(ISpeakeasyHttpClient client, Func<Codat.Lending.Models.Components.Security>? securitySource, string serverUrl, SDKConfig config)
        {
            _client = client;
            _securitySource = securitySource;
            _serverUrl = serverUrl;
            SDKConfiguration = config;
            AccountTransactions = new AccountTransactions(_client, _securitySource, _serverUrl, SDKConfiguration);
            DirectCosts = new DirectCosts(_client, _securitySource, _serverUrl, SDKConfiguration);
            JournalEntries = new JournalEntries(_client, _securitySource, _serverUrl, SDKConfiguration);
            Journals = new Journals(_client, _securitySource, _serverUrl, SDKConfiguration);
            Transfers = new Transfers(_client, _securitySource, _serverUrl, SDKConfiguration);
        }
    }
}