
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace CodatSyncCommerce.Models.Shared
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GroupingPeriod
    {

        /// <summary>
        /// Array of grouping period options.
        /// </summary>
        [JsonProperty("groupingPeriodOptions")]
        public List<string>? GroupingPeriodOptions { get; set; }

        /// <summary>
        /// Grouping period i.e. Daily sales.
        /// </summary>
        [JsonProperty("selectedGroupingPeriod")]
        public string? SelectedGroupingPeriod { get; set; }
    }
}