
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace CodatSyncCommerce.Models.Shared
{
    using Newtonsoft.Json;
    
    public class SupportedFeature
    {

        [JsonProperty("featureState")]
        public FeatureState FeatureState { get; set; } = default!;

        [JsonProperty("featureType")]
        public FeatureType FeatureType { get; set; } = default!;
    }
}