//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Platform.Models.Components
{
    using Codat.Platform.Utils;
    using Newtonsoft.Json;
    
    public class IssueLinks
    {

        /// <summary>
        /// A link to the validation logs, providing details on any errors or warnings encountered.
        /// </summary>
        [JsonProperty("logs")]
        public string? Logs { get; set; }

        /// <summary>
        /// A link to the company&apos;s past data read history in the Codat portal.
        /// </summary>
        [JsonProperty("portal")]
        public string? Portal { get; set; }

        /// <summary>
        /// A link to Codat&apos;s documentation with additional information on how to troubleshoot this issue.
        /// </summary>
        [JsonProperty("readMore")]
        public string? ReadMore { get; set; }
    }
}