//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Platform.Models.Components
{
    using Codat.Platform.Models.Components;
    using Codat.Platform.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class PushOptionProperty
    {
        /// <summary>
        /// The option type.
        /// </summary>
        [JsonProperty("type")]
        public PushOptionType Type { get; set; } = default!;

        /// <summary>
        /// The property's display name.
        /// </summary>
        [JsonProperty("displayName")]
        public string DisplayName { get; set; } = default!;

        /// <summary>
        /// A description of the property.
        /// </summary>
        [JsonProperty("description")]
        public string Description { get; set; } = default!;

        /// <summary>
        /// The property is required if `True`.
        /// </summary>
        [JsonProperty("required")]
        public bool Required { get; set; } = default!;

        [JsonProperty("properties")]
        public Dictionary<string, PushOptionProperty>? Properties { get; set; } = null;

        [JsonProperty("options")]
        public List<PushOptionChoice>? Options { get; set; } = null;

        [JsonProperty("validation")]
        public PushValidationInfo? Validation { get; set; }
    }
}