//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Lending.Models.Components
{
    using Codat.Lending.Models.Components;
    using Codat.Lending.Utils;
    using Newtonsoft.Json;

    public class AccountTransactionLine
    {
        /// <summary>
        /// Description of the account transaction.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Links an account transaction line to the underlying record that created it.
        /// </summary>
        [JsonProperty("recordRef")]
        public AccountTransactionLineRecordRef? RecordRef { get; set; }

        /// <summary>
        /// Amount in the bill payment currency.
        /// </summary>
        [JsonProperty("amount")]
        public decimal? Amount { get; set; }
    }
}