//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Lending.Models.Components
{
    using Codat.Lending.Models.Components;
    using Codat.Lending.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public class OrderLineItem
    {
        /// <summary>
        /// A unique, persistent identifier for this record.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// Number of units of the product sold.<br/>
        /// For refunds, quantity is negative.
        /// </summary>
        [JsonProperty("quantity")]
        public decimal? Quantity { get; set; }

        /// <summary>
        /// Percentage rate (from 0 to 100) of any sales tax applied to the unit price.
        /// </summary>
        [JsonProperty("taxPercentage")]
        public decimal? TaxPercentage { get; set; }

        /// <summary>
        /// Total amount of the line item, including discounts and tax.
        /// </summary>
        [JsonProperty("totalAmount")]
        public decimal? TotalAmount { get; set; }

        /// <summary>
        /// Total amount of tax applied to the line item, factoring in any discounts.
        /// </summary>
        [JsonProperty("totalTaxAmount")]
        public decimal? TotalTaxAmount { get; set; }

        /// <summary>
        /// Price per unit of goods or services, excluding discounts and tax.
        /// </summary>
        [JsonProperty("unitPrice")]
        public decimal? UnitPrice { get; set; }

        /// <summary>
        /// Taxes breakdown as applied to order lines.
        /// </summary>
        [JsonProperty("taxes")]
        public List<TaxComponentAllocation>? Taxes { get; set; }

        /// <summary>
        /// Reference that links the line item to the correct product details.
        /// </summary>
        [JsonProperty("productRef")]
        public ProductRef? ProductRef { get; set; }

        /// <summary>
        /// Reference that links the line item to the specific version of product that has been ordered.
        /// </summary>
        [JsonProperty("productVariantRef")]
        public ProductVariantRef? ProductVariantRef { get; set; }

        [JsonProperty("discountAllocations")]
        public List<OrderDiscountAllocation>? DiscountAllocations { get; set; }
    }
}