///
 /// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 ///

namespace Codat.Models.DataIntegrity;
using Codat.Utils;
using Codat.Models.Shared;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Net;
using System.Net.Http;
using System.Text;

/*
using Codat.Models.Shared;
*/

public class GetDataIntegrityDetailsRequest
{
    [JsonProperty("companyId")]
    public string CompanyId { get; set; }
    
    [JsonProperty("dataType")]
    public DataIntegrityDataTypeEnum DataType { get; set; }
    
    [JsonProperty("orderBy")]
    public string? OrderBy { get; set; }
    
    [JsonProperty("page")]
    public int Page { get; set; }
    
    [JsonProperty("pageSize")]
    public int? PageSize { get; set; }
    
    [JsonProperty("query")]
    public string? Query { get; set; }
    
    internal HttpRequestMessage BuildHttpRequestMessage(string operationId)
    {
        if("get-data-integrity-details" == operationId)
        {
            // serialize query parameters
            var queryParams = new List<string>();
            queryParams.Add(QueryParamSerializer.Serialize("simple",false, "companyId", "", this.CompanyId));
            queryParams.Add(QueryParamSerializer.Serialize("simple",false, "dataType", "", this.DataType));
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "orderBy", "", this.OrderBy));
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "page", "", this.Page));
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "pageSize", "", this.PageSize));
            queryParams.Add(QueryParamSerializer.Serialize("form",true, "query", "", this.Query));

            var queryParamString = $"?{String.Join("&", queryParams)}";
            // add path params
            
            var companyId = PathParamSerializer.Serialize("simple", false, this.CompanyId);
            
            var dataType = PathParamSerializer.Serialize("simple", false, this.DataType);
            
            
            
            
            var message = new HttpRequestMessage(HttpMethod.Get, $"/data/companies/{companyId}/assess/dataTypes/{dataType}/dataIntegrity/details" + queryParamString);
            return message;
        }
        throw new ArgumentException($"Attempt to build HttpRequestMessage for invalid operationId [{operationId}] for request type [GetDataIntegrityDetailsRequest]");
    }
}
