//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Sync.Payables.V1.Models.Components
{
    using Codat.Sync.Payables.V1.Utils;
    using Newtonsoft.Json;
    
    public class HalRef
    {

        /// <summary>
        /// Uri hypertext reference.
        /// </summary>
        [JsonProperty("href")]
        public string? Href { get; set; }
    }
}