
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace CodatBankFeeds.Models.Operations
{
    using CodatBankFeeds.Utils;
    
    public class GetCreateOperationRequest
    {

        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=companyId")]
        public string CompanyId { get; set; } = default!;

        /// <summary>
        /// Push operation key.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=pushOperationKey")]
        public string PushOperationKey { get; set; } = default!;
    }
}