
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Codat.Models.Shared
{
    using Newtonsoft.Json;
    
    public class FinancialMetricPeriodsInputs
    {
    /// <summary>
    /// The name of the metric input e.g. “Current Assets”, “Capital Expenditure”.
    /// </summary>
        
        [JsonProperty("name")]
        public string? Name { get; set; }
        
    /// <summary>
    /// The positive or negative number of the input value.
    /// </summary>
        
        [JsonProperty("value")]
        public float? Value { get; set; }
        
    }
}