
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Codat.Models.Shared
{
    using Newtonsoft.Json;
    
/// <summary>
/// A source reference containing the `sourceType` object "Banking".
/// </summary>
    public class SourceRef
    {
        
        [JsonProperty("sourceType")]
        public string? SourceType { get; set; }
        
    }
}