//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Codat.Sync.Payables.Utils
{
    /// <summary>
    /// SDK constants for version information and language identification.
    /// </summary>
    public static class Constants
    {
        /// <summary>
        /// The language identifier for this SDK.
        /// </summary>
        public const string Language = "csharp";

        /// <summary>
        /// The version of the SDK.
        /// </summary>
        public const string SdkVersion = "10.1.0";

        /// <summary>
        /// The version of the SDK generator used to create this SDK.
        /// </summary>
        public const string SdkGenVersion = "2.812.2";

        /// <summary>
        /// The version of the OpenAPI document used to generate this SDK.
        /// </summary>
        public const string OpenApiDocVersion = "3.0.0";
    }
}

